"""empty message

Revision ID: 63c605ac5252
Revises: 
Create Date: 2018-11-24 19:32:15.857784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63c605ac5252'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admin_user',
    sa.Column('adminId', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adminId'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], )
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(length=48), nullable=True),
    sa.Column('longitude', sa.String(length=48), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dateTime'),
    sa.UniqueConstraint('latitude'),
    sa.UniqueConstraint('longitude')
    )
    op.create_table('zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.String(length=48), nullable=True),
    sa.Column('longitude', sa.String(length=48), nullable=True),
    sa.Column('radius', sa.Integer(), nullable=True),
    sa.Column('dateStart', sa.DateTime(), nullable=True),
    sa.Column('dateEnd', sa.DateTime(), nullable=True),
    sa.Column('timeStart', postgresql.TIME(), nullable=True),
    sa.Column('timeEnd', postgresql.TIME(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dateEnd'),
    sa.UniqueConstraint('dateStart'),
    sa.UniqueConstraint('latitude'),
    sa.UniqueConstraint('longitude'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('radius'),
    sa.UniqueConstraint('timeEnd'),
    sa.UniqueConstraint('timeStart')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zone')
    op.drop_table('location')
    op.drop_table('admin_user')
    op.drop_table('user')
    op.drop_table('admin')
    # ### end Alembic commands ###
