"""empty message

Revision ID: 831fe751fc56
Revises: 63c605ac5252
Create Date: 2018-12-02 14:08:39.695551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831fe751fc56'
down_revision = '63c605ac5252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('key', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'key')
    # ### end Alembic commands ###
