"""empty message

Revision ID: cfa82498d07b
Revises: 831fe751fc56
Create Date: 2018-12-02 14:40:50.281700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa82498d07b'
down_revision = '831fe751fc56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_name_key', 'admin', type_='unique')
    op.drop_constraint('location_dateTime_key', 'location', type_='unique')
    op.drop_constraint('location_latitude_key', 'location', type_='unique')
    op.drop_constraint('location_longitude_key', 'location', type_='unique')
    op.drop_constraint('user_name_key', 'user', type_='unique')
    op.drop_constraint('zone_dateEnd_key', 'zone', type_='unique')
    op.drop_constraint('zone_dateStart_key', 'zone', type_='unique')
    op.drop_constraint('zone_latitude_key', 'zone', type_='unique')
    op.drop_constraint('zone_longitude_key', 'zone', type_='unique')
    op.drop_constraint('zone_name_key', 'zone', type_='unique')
    op.drop_constraint('zone_radius_key', 'zone', type_='unique')
    op.drop_constraint('zone_timeEnd_key', 'zone', type_='unique')
    op.drop_constraint('zone_timeStart_key', 'zone', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('zone_timeStart_key', 'zone', ['timeStart'])
    op.create_unique_constraint('zone_timeEnd_key', 'zone', ['timeEnd'])
    op.create_unique_constraint('zone_radius_key', 'zone', ['radius'])
    op.create_unique_constraint('zone_name_key', 'zone', ['name'])
    op.create_unique_constraint('zone_longitude_key', 'zone', ['longitude'])
    op.create_unique_constraint('zone_latitude_key', 'zone', ['latitude'])
    op.create_unique_constraint('zone_dateStart_key', 'zone', ['dateStart'])
    op.create_unique_constraint('zone_dateEnd_key', 'zone', ['dateEnd'])
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.create_unique_constraint('location_longitude_key', 'location', ['longitude'])
    op.create_unique_constraint('location_latitude_key', 'location', ['latitude'])
    op.create_unique_constraint('location_dateTime_key', 'location', ['dateTime'])
    op.create_unique_constraint('admin_name_key', 'admin', ['name'])
    # ### end Alembic commands ###
